export const GET_POSTS = 'GET_POSTS';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_FOR_CATEGORY = 'FETCH_POST_FOR_CATEGORY';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const VOTE_ON_POST = 'VOTE_ON_POST';
export const UP_VOTE_POST = 'UP_VOTE_POST';
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST';
export const DELETE_POST = 'DELETE_POST';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_COMMENTS_FOR_POST = 'FETCH_COMMENTS_FOR_POST';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const POST_COMMENT = 'POST_COMMENT';
export const VOTE_ON_COMMENT = 'VOTE_ON_COMMENT';
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT';
export const DOWN_VOTE_COMMENT = 'DOWN_VOTE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const SORT_POSTS = 'SORT_POSTS';
export const SORT_COMMENTS = 'SORT_COMMENTS';

export const START_EDITING_COMMENT = 'START_EDITING_COMMENT';
export const STOP_EDITING_COMMENT = 'STOP_EDITING_COMMENT';
